export interface UserDocument {
  _id?: string; // Automatically generated by MongoDB
  email: string;
  passwordHash: string;
  // Matches your exact role list from firestore.rules
  role: 'super-admin' | 'school-head' | 'sub-region-admin' | 'teacher' | 'student' | 'developer';
  schoolId?: string; // Linked context for school-specific rules
  createdAt: Date;
}
